# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MovieList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CocoaLumberjack/Swift'
  pod 'RealmSwift'
  pod 'Alamofire'

end
